package com.foo.edu.reportboard.model;
// Generated 2018/02/11 6:29:27 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * CommentImages generated by hbm2java
 */
@Entity
@Table(name = "comment_images")
@NamedQueries ({
	@NamedQuery(name="CommentImages.findAll" ,query="SELECT ci FROM CommentImages ci ORDER BY ci.commentImageId ASC"),
	@NamedQuery(name="CommentImages.findById",query="SELECT ci FROM CommentImages ci WHERE ci.commentImageId = :commentImageId")
})
public class CommentImages implements java.io.Serializable {

	private static final long serialVersionUID = 5282400251887935814L;
	private int commentImageId;
	private Comments comments;
	private String imageName;
	private byte[] content;

	public CommentImages() {
	}

	public CommentImages(int commentImageId, byte[] content) {
		this.commentImageId = commentImageId;
		this.content = content;
	}

	public CommentImages(int commentImageId, Comments comments, String imageName, byte[] content) {
		this.commentImageId = commentImageId;
		this.comments = comments;
		this.imageName = imageName;
		this.content = content;
	}

	@Id

	@Column(name = "comment_image_id", unique = true, nullable = false)
	public int getCommentImageId() {
		return this.commentImageId;
	}

	public void setCommentImageId(int commentImageId) {
		this.commentImageId = commentImageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "comment_id")
	public Comments getComments() {
		return this.comments;
	}

	public void setComments(Comments comments) {
		this.comments = comments;
	}

	@Column(name = "image_name", length = 128)
	public String getImageName() {
		return this.imageName;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	@Column(name = "content", nullable = false)
	public byte[] getContent() {
		return this.content;
	}

	public void setContent(byte[] content) {
		this.content = content;
	}

}
