package com.foo.edu.reportboard.model;
// Generated 2018/02/11 6:29:27 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * ReportImages generated by hbm2java
 */
@Entity
@Table(name = "report_images")
@NamedQueries ({
	@NamedQuery(name="ReportImages.findAll" ,query="SELECT ri FROM ReportImages ri ORDER BY ri.reportImageId ASC"),
	@NamedQuery(name="ReportImages.findById",query="SELECT ri FROM ReportImages ri WHERE ri.reportImageId = :reportImageId")
})
public class ReportImages implements java.io.Serializable {
	private static final long serialVersionUID = 5184792304693725922L;
	private int reportImageId;
	private Reports reports;
	private String imageName;
	private byte[] content;

	public ReportImages() {
	}

	public ReportImages(int reportImageId, byte[] content) {
		this.reportImageId = reportImageId;
		this.content = content;
	}

	public ReportImages(int reportImageId, Reports reports, String imageName, byte[] content) {
		this.reportImageId = reportImageId;
		this.reports = reports;
		this.imageName = imageName;
		this.content = content;
	}

	@Id

	@Column(name = "report_image_id", unique = true, nullable = false)
	public int getReportImageId() {
		return this.reportImageId;
	}

	public void setReportImageId(int reportImageId) {
		this.reportImageId = reportImageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "report_id")
	public Reports getReports() {
		return this.reports;
	}

	public void setReports(Reports reports) {
		this.reports = reports;
	}

	@Column(name = "image_name", length = 128)
	public String getImageName() {
		return this.imageName;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	@Column(name = "content", nullable = false)
	public byte[] getContent() {
		return this.content;
	}

	public void setContent(byte[] content) {
		this.content = content;
	}

}
